config/routes.rb
GarageProject::Application.routes.draw do

  devise_for :users

  resources :tasks
  resources :projects

  concern :the_role, TheRole::AdminRoutes.new

  namespace :admin do
    concerns :the_role
  end

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :tasks, dependent: :destroy
	validates_presence_of :name
	
	# validates :user,    presence: true
	# validates :title,   presence: true, uniqueness: true
	# validates :content, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  acts_as_role
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates_presence_of :name, :project, :priority
end

app/models/user.rb
class User < ActiveRecord::Base
	devise :database_authenticatable, :registerable, :confirmable, :recoverable, stretches: 20
	has_role
	has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include TheRole::Controller

  protect_from_forgery

  def access_denied
    flash[:error] = t('the_role.access_denied')
    redirect_to(:back)
  end
  
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
require 'pry'
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    prior = {1 => "1 - ASAP", 2 => "2 - Very high", 3 => "3 - High", 4 => "4 - Medium", 5 => "5 - Low" }
    @projects = Project.all
    priority, effect, task = params[:priority], params[:effect], params[:task]
    if priority
      p = priority[0].to_i
      return false if p<1 || p>5
      task = Task.find(task) 
      if effect == "up"
        task.priority = prior[p-1]
      else
        task.priority = prior[p+1]
      end
      task.save
      redirect_to projects_url
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    tasks=Task.all.where(project_id: @project.id)
    @names=""
    tasks.each do |task|
      @names+=task.name+"; "
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  # skip_before_action :verify_authenticity_token
  # respond_to :html, :json
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    # @task = Task.find(params[:id])
    # @task.update_attributes(params[:done])
    # respond_with @task
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
        # redirect_to projects_url
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :deadline, :done, :project_id, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GarageProject</title>
   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/assets/ruby.ico" type="image/x-icon">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
</head>
<body>
<div class="container">
	<div class="headers">
		<a href="/"><h1>simple todo lists</h1></a>
		<a href="/"><p>from ruby garage</p></a>
	</div>
	<% flash.each do |name, message| %>
		<div class="alert alert-<%= name == :notice ? 'success' : 'error' %>">
			<a class="close" data-dismiss="alert">x</a>
			<%= message %>
		</div>
	<% end %>
	<div class="raw">
		<div class="col-md-2"></div>
		<div class="col-md-8"><%= yield %></div>
		<div class="col-md-2"></div>
	</div>
</div>
</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for @project, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.input :name %>
  <%= f.association :tasks, collection: Task.all.where(project_id: @project.id) %>
  <%= link_to 'Add new task', new_task_path,:class => 'btn btn-default  new-task-btn' %>
  <%= link_to 'Delete task', tasks_path,:class => 'btn btn-default  new-task-btn' %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>  
<% @projects.each do |project| %>
<script type="text/javascript">
$(document).ready(function(){
  $(".navbar-header<%= project.id %>").click(function(){
    alert('Last time project was updated at:\n <%= project.created_at %>');
  });
  $('#addTask<%= project.id %>').click(function(){
    $(this).attr('href', $(this).attr('href') + $('.form-control<%= project.id %>').val());
  });
  // console.log("<%= @priority %>,<%= @effect %>")
})
</script>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header navbar-header<%= project.id %>">
      <a class="navbar-brand" href="#"><%= project.name %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to '', edit_project_path(project), :class => 'edit-btn' %></li>
        <li><%= link_to '',
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn-delete' %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="panel panel-default">
  <div class="panel-body">
    <div class="input-group">
      <img src="/assets/green-plus.png">
      <%= text_field :task, :name, :class => 'form-control form-control'+project.id.to_s %>
      <span class="input-group-btn">
        <%= link_to 'Add Task', new_task_path(projectId: project.id, taskName: ""),:class => "btn btn-success", id:"addTask"+project.id.to_s %>
        <!-- <button class="btn btn-default" type="button">Add Task</button> -->
      </span>
    </div><!-- /input-group -->
  </div>
</div>
<table class="table table<%= project.id %> table-bordered table-hover">
    <% Task.where(project_id: project.id).order(:done).order(:priority).each do |task| %>
    <script type="text/javascript">
    $(document).ready(function(){
      $(".<%= task.id %>").hover(
        function() {  $(".task-btns<%= task.id %>").css('visibility','visible');   },
        function() {  $(".task-btns<%= task.id %>").css('visibility','hidden');   }
      );
    });
    </script>
      <% if task.deadline.past? && !task.done %>
        <tr class="<%= task.id %> red">
            <td width="20"><i class='icon-exclamation-sign'></i></td>
      <% else %>
        <tr class="<%= task.id %>">
            <td width="20"><%= best_in_place task, :done, type: :checkbox,  collection: [raw("<i class='icon-check-empty'></i>"), raw("<i class='icon-check'></i>")], remote: true %></td>
            <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
      <% end %>
        <td><%= task.name %></td>
        <td width="110">
          <div class="task-btns task-btns<%= task.id %>">
            <div class="arrows">
              <%= link_to "", projects_path(task: task.id, priority: task.priority, effect: 'up'), :class => 'priority-arrows', name: "upper" %>
              <%= link_to "", projects_path(task: task.id, priority: task.priority, effect: 'down'), :class => 'priority-arrows', name: "lower" %>
            </div>
            <%= link_to "", edit_task_path(task), :class => 'task-edit' %>
            <%= link_to "", task_path(task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'task-delete' %>
          </div>
        </td>
      </tr>
    <% end %>
</table>
<% end %>

<%= link_to 'Add TODO List',
            new_project_path,
            :class => 'btn btn-primary new-proj' %>
            <footer><p>©Ruby Garage</p></footer>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @project.name %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong>Tasks:</strong></dt>
  <dd><%= @names %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_path(@project), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_path(@project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for @task, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.input :name, input_html: { value: params[:taskName] } %>
  <%= f.input :deadline %>
  <%= f.input :priority, collection: ["1 - ASAP", "2 - Very high", "3 - High", "4 - Medium", "5 - Low"], as: :select %>
  <%= f.input :done %>
  <%= f.association :project, selected: params[:projectId] %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:deadline) %></th>
      <th><%= model_class.human_attribute_name(:done) %></th>
      <th><%= model_class.human_attribute_name(:project_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.id, task_path(task) %></td>
        <td><%= task.name %></td>
        <td><%= task.deadline %></td>
        <td><%= task.done %></td>
        <td><%= task.project_id %></td>
        <td><%=l task.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_task_path(task), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      task_path(task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_task_path,
            :class => 'btn btn-primary' %>

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @task.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deadline) %>:</strong></dt>
  <dd><%= @task.deadline %></dd>
  <dt><strong><%= model_class.human_attribute_name(:done) %>:</strong></dt>
  <dd><%= @task.done %></dd>
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= @task.project_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_task_path(@task), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              task_path(@task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>